# Generated by Django 5.0.6 on 2024-05-22 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('libelleOption', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('libelleSection', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TypeFraisAcademique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom_frais', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('libellePromotion', models.CharField(blank=True, max_length=100, null=True)),
                ('vacationPromotion', models.CharField(choices=[('jour', 'Jour'), ('soir', 'Soir')], max_length=10)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='params_basic.option')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FraisAcademique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom_frais', models.CharField(blank=True, max_length=255)),
                ('montant_frais', models.IntegerField(default=1)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='params_basic.promotion')),
                ('type_frais_academique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='params_basic.typefraisacademique')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='option',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='params_basic.section'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matricule', models.CharField(blank=True, max_length=255)),
                ('nom', models.CharField(blank=True, max_length=255)),
                ('postnom', models.CharField(blank=True, max_length=255)),
                ('prenom', models.CharField(blank=True, max_length=255)),
                ('genre', models.CharField(blank=True, max_length=10)),
                ('date_de_naissance', models.DateTimeField()),
                ('fk_promotion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='params_basic.promotion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FraisAcademiqueStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status_paiement', models.BooleanField(default=False)),
                ('frais_academique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='params_basic.fraisacademique')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='params_basic.student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
